config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    authenticated :user do
    root 'pages#home', as: :authenticated_root
    get 'about' => 'pages#about' #about_path
    get 'search' => 'pages#search'
    get 'results' => 'pages#show'
    resources :pages
    resources :spreadsheets

  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
    get 'about' => 'pages#about' #about_path
  end
end

end

app/models/search.rb
#class Search < ActiveRecord::Base
#	attribute :search
#end

app/models/spreadsheet.rb
class Spreadsheet < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :company, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :company, :email, :current_password, :password, :password_confirmation) }
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
def new
    @search = Search.new
end

def home
  @spreadsheets = Spreadsheet.all

  if params[:q].present?
    @jobs = IndeedAPI.search_jobs(q: params[:q])
    @results = @jobs.results
    #@description = @results.company
  else
    @jobs = []
    @results =[]
  end

end

def create
  @search = Search.new(params[:contact])
  @search.request = request
  if @search.deliver
  else
    flash.now[:error] = 'Something went wrong, please try your search again.'
    render :new
  end
end

  def about
  end

def search
  @spreadsheet = Spreadsheet.create(description:'test')
  redirect_to '/spreadsheets/'+@spreadsheet.id.to_s
end


end

app/controllers/spreadsheets_controller.rb
class SpreadsheetsController < ApplicationController
  before_action :set_spreadsheet, only: [:show, :edit, :update, :destroy]

  # GET /spreadsheets
  # GET /spreadsheets.json
  def index
    @spreadsheets = Spreadsheet.all
  end

  # GET /spreadsheets/1
  # GET /spreadsheets/1.json
  def show
  end

  # GET /spreadsheets/new
  def new
    @spreadsheet = Spreadsheet.new
  end

  # GET /spreadsheets/1/edit
  def edit
  end

  # POST /spreadsheets
  # POST /spreadsheets.json
  def create
    @spreadsheet = Spreadsheet.new(spreadsheet_params)

    if @spreadsheet.save
      redirect_to @spreadsheet, notice: 'Spreadsheet was successfully created.' 
      render :show, status: :created, location: @spreadsheet
    else
      render :new 
        
    end
    
  end

  # PATCH/PUT /spreadsheets/1
  # PATCH/PUT /spreadsheets/1.json
  def update
    
    if @spreadsheet.update(spreadsheet_params)
      redirect_to @spreadsheet, notice: 'Spreadsheet was successfully updated.'
    else
      render :edit
    end
  
  end

  # DELETE /spreadsheets/1
  # DELETE /spreadsheets/1.json
  def destroy
    @spreadsheet.destroy
    redirect_to spreadsheets_url, notice: 'Spreadsheet was successfully destroyed.' 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spreadsheet
      @spreadsheet = Spreadsheet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spreadsheet_params
      params.require(:spreadsheet).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/spreadsheets_helper.rb
module SpreadsheetsHelper
end

app/views/layouts/_app_header.html.erb
<header>
       <div class = "container">
        <!--<h1>Headline text</h1>-->
            <div class="top-left-nav">[LOGO NAME]</div>
            <div class="search-bar">
              <%= form_tag('/', method: 'get', class: "search-bar") do %>
              <%= text_field_tag (:q), nil, :placeholder => ' Search by job title', class: "search-input-field"  %>
              <%= submit_tag('Go') %>
            <% end %>
            </div>
    <div class="top-nav">
<!--<a href="#" class="gear-icon">&nbsp;&nbsp;&nbsp;&nbsp;</a> -->
      <ul class="nav navbar-nav" >
         <li >
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= "#{current_user.name}" %> <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "Settings", edit_user_registration_path %></li>
                  <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            </ul>

      </ul>



      <!-- margin-right feedback 20, referrals 10 -->
    </div>
</div>
</header>

app/views/layouts/_header.html.erb
<head>

  <title>Sales Gen</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://ssl.gstatic.com/docs/script/css/add-ons.css">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>



    <!-- /.navbar-collapse -->
 

  </div><!-- /.container -->
</nav>

app/views/layouts/_header_old.html.erb
<head>

  <title>Sales Gen</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://ssl.gstatic.com/docs/script/css/add-ons.css">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>

<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <div class="container">
  
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Spreadsheets", root_path, class: 'navbar-brand' %>
    </div>

    Collect the nav links, forms, and other content for toggling
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path%></li>
        <li><%= link_to "About", about_path%></li>
        <% if user_signed_in? %>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>˜
        <% else %>
          <li>  <%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>

    <!-- /.navbar-collapse -->
 

  </div><!-- /.container -->
</nav>

app/views/layouts/_loginheader.html.erb
<% if user_signed_in? %>
          <%else %>
<div class="login-container">
<img src="http://placehold.it/350x150" class="login-img">
</div>

<div class="bottom-link"><div class="signupnow">Don't have an account? <a href="#"><strong>Register today</strong></a>.</div></div>          
          <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/header' %>
<body>
	
	<!--<div class="container">-->
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	<!--</div>-->

</body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>

app/views/pages/home.html.erb
<% if user_signed_in? %>



<% else %>
 <p>  <%= link_to "Sign in", new_user_session_path %></p>
<% end %>

<%= render 'layouts/app_header' %>

<div class="container">
	<div class='box'>
		<h2>New Opportunities for <%= "#{current_user.company}" %></h2>
		<div class="nav-divider"></div>

			<div class="form-group">
			
				<% @results.each do |job| %>
					<div class="results-container">
						<div class="search-details">
							<div class="right-details">
								<%= link_to job.job_title, job.url, target: "_blank" %>
								
							</div>
							<div>
								<span class="result-details"><%= link_to job.company, "https://www.google.com/search?q="+job.company+" in "+job.formatted_location, target: "_blank" %></span>,
								<small><%= job.formatted_location %></small>
								<br />
								<small class="posted-time">Posted <%= job.formatted_relative_time %></small>
							</div>
						
							<p class="snippet"><%= job.snippet %></p>
							<hr>
						</div>
						

						
						
					</div>
				
				<% end %>
		   </div>

	</div>
</div>

app/views/pages/home_with_saved_search.html.erb
<div class = 'saved-searches'>
	Recent Searches
	<div class="nav-divider"></div>
	<%= render 'spreadsheets/result' %>
</div>

app/views/pages/show.html.erb
<%= @spreadsheet.description %>

app/views/spreadsheets/_form.html.erb
<%= form_for(@spreadsheet) do |f| %>
  <% if @spreadsheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spreadsheet.errors.count, "error") %> prohibited this spreadsheet from being saved:</h2>

      <ul>
      <% @spreadsheet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/spreadsheets/_result.html.erb
<div class = "saved-search-queries">
	<% @spreadsheets.each do |spreadsheet| %>
		<p><%= link_to "#{spreadsheet.description}", spreadsheet %>
	 		<!--<span class="small">-->
		</p>
		<hr style="margin-top:-20px">
	<% end %>
</div>

app/views/spreadsheets/edit.html.erb
<h1>Editing Spreadsheet</h1>

<%= render 'form' %>

<%= link_to 'Show', @spreadsheet %> |
<%= link_to 'Back', spreadsheets_path %>

app/views/spreadsheets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Spreadsheets</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spreadsheets.each do |spreadsheet| %>
      <tr>
        <td><%= spreadsheet.description %></td>
        <td><%= link_to 'Show', spreadsheet %></td>
        <td><%= link_to 'Edit', edit_spreadsheet_path(spreadsheet) %></td>
        <td><%= link_to 'Destroy', spreadsheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Spreadsheet', new_spreadsheet_path %>

app/views/spreadsheets/new.html.erb
<h1>New Spreadsheet</h1>

<%= render 'form' %>

<%= link_to 'Back', spreadsheets_path %>

app/views/spreadsheets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @spreadsheet.description %>
</p>

<%= link_to 'Edit', edit_spreadsheet_path(@spreadsheet) %> |
<%= link_to 'Back', spreadsheets_path %>